[build]
  # Point this to your Nigeria API folder
  base = "spokes/nigeria/apps/api"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "src/routes"
  node_bundler = "esbuild"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/sovryn/:splat"
  status = 200
  force = true
